Paggio.html do
  head do
    script type: "text/javascript", src: "script.js"
    #link rel: "stylesheet", href: "style.css"
    link rel: "stylesheet", href: "https://unpkg.com/xp.css"
    link rel: 'icon', type: 'image/x-icon', href: 'favicon.ico'
    style do
      rule '.window-body' do
        resize 'both'
        overflow 'auto'
        width 250.px
        height 250.px
        margin right: 8.px
        margin bottom: 5.px
      end
      rule '.window' do
        display 'inline-block'
      end
      rule '.title-bar-text' do
        user select: 'none'
      end
    end
  end
  #img.justicar(src: '/justicar.png', alt: 'Justicar', height: '400px')
  #h1 { "Hello world from Justicar" }
  hr
  5.times do
  div.window do
    div.draggable(class: 'title-bar') do
      div(class: 'title-bar-text') { "A Window With Stuff In It" }
      div(class: 'title-bar-controls') do
        #button("aria-label": "Minimize")
        button("aria-label": "Maximize")
        #button("aria-label": "Close")
      end
    end
    div(class: "window-body") { "Woo stuff and things" }
  end
  end
=begin
  h2.paggio do
    'Hello world from Paggi!'
  end
  p.paggio do
    "This part was generated by Paggio in HTML :)"
  end
=end
end
