Paggio.html do
  head do
    link rel: "stylesheet", href: "style.css"
    link rel: "stylesheet", href: "https://unpkg.com/xp.css"
    link rel: 'icon', type: 'image/x-icon', href: 'favicon.ico'
    style do
      rule '.window-body' do
        resize 'both'
        overflow 'auto'
        width 250.px
        height 250.px
        margin right: 8.px
        margin bottom: 5.px
      end
      rule '.window' do
        display 'inline-block'
      end
      rule '.title-bar-text' do
        user select: 'none'
      end
    end
  end
  body do
    #img.justicar(src: '/justicar.png', alt: 'Justicar', height: '400px')
    #h1 { "Hello world from Justicar" }
    div do
      h1 { "Catgirls Rodeo" }
    end
    img(src: 'rodeo_by_urasato.png').rodeo
    div.window_handler do
      #25.times do
      #  div.guide(style: "flex-basis: #{(220..350).to_a.sample}px") { 'red' }
      #end
      #end
      25.times do
        div.window do
          div.draggable(class: 'title-bar') do
            div(class: 'title-bar-text') { "A Window With Stuff In It" }
            div(class: 'title-bar-controls') do
              #button("aria-label": "Minimize")
              button("aria-label": "Maximize").maximize
              button("aria-label": "Close").close
            end
          end
          div(class: "window-body", style: "width: #{(250..450).to_a.sample}px") { 
            p { "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed elit lacinia orci maximus lobortis nec sed tellus. Aenean tempus, dui sit amet scelerisque condimentum, est odio feugiat dui, et suscipit dui lectus eget elit. Mauris sit amet mollis massa. Nullam vel fringilla lorem. Suspendisse semper nec nisi at pretium. Cras venenatis ex vitae orci porta facilisis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus euismod justo in metus sagittis lacinia. Nunc ante turpis, hendrerit vel lobortis nec, viverra at justo. Fusce mollis nec ipsum eu porttitor. Morbi sapien neque, lobortis at odio vitae, porttitor finibus turpis. Pellentesque sit amet urna nisl. Nulla consequat mi at hendrerit euismod. Sed sodales auctor eros." }
            p { "Suspendisse tincidunt luctus lacinia. In tincidunt mauris ac libero posuere vestibulum. Aenean ut commodo augue. Suspendisse fringilla euismod purus sed venenatis. In lacinia accumsan cursus. Vestibulum lobortis malesuada nisi, ut blandit lacus consequat a. Morbi non neque eu augue cursus imperdiet. Nulla non lectus et ex blandit eleifend vel nec felis. Fusce ultrices orci et sapien dictum, sed vehicula felis volutpat. Maecenas quis lacus convallis, pulvinar nunc id, tempus turpis. Morbi vitae sodales odio. Fusce id massa varius, pulvinar lectus ac, facilisis ex. Quisque condimentum feugiat nibh, volutpat hendrerit magna vehicula sed." }
            p { "Pellentesque non accumsan ante, a ultrices eros. Aliquam efficitur elit id sapien condimentum, a tempor nunc lobortis. Nulla pulvinar egestas posuere. Donec sit amet ex quis nisl vulputate venenatis. Integer dui augue, vestibulum a justo id, tristique mattis massa. Sed rutrum venenatis erat, gravida rutrum lorem tincidunt ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus quam sapien, tempus tempus risus a, suscipit condimentum erat. Quisque tincidunt eget ligula ut blandit. Nulla mattis tincidunt felis sodales malesuada. Phasellus volutpat maximus diam et congue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam vitae efficitur urna. Aenean arcu ex, mollis ac dictum at, dictum pellentesque enim. Morbi aliquam consectetur augue at luctus." }
            p { "Vivamus aliquet ipsum sed sapien maximus interdum. Nulla congue posuere consectetur. Cras vitae porttitor arcu. Ut consectetur lorem risus, commodo fringilla mauris mollis nec. Fusce dignissim elit a sem mattis, vitae faucibus libero accumsan. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec auctor turpis ac gravida aliquet." }
            p { "Ut mollis felis vitae ante ultrices, ac auctor nunc elementum. Quisque in velit quis arcu vestibulum vulputate ut at tortor. Aliquam eu scelerisque justo. Quisque tincidunt scelerisque dui eu pharetra. Vestibulum tincidunt, mi congue aliquet maximus, arcu quam sodales libero, ultrices convallis nibh nunc varius nisl. Sed elementum ultricies eleifend. Sed lacinia non massa id auctor." }
          }
        end
      end
=begin
  h2.paggio do
    'Hello world from Paggi!'
  end
  p.paggio do
    "This part was generated by Paggio in HTML :)"
  end
=end
    end
  end
    script type: "text/javascript", src: "script.js"
end
