target["index.html"] = Paggio.html do
  head do
    link rel: "stylesheet", href: "https://unpkg.com/xp.css"
    link rel: "stylesheet", href: "style.css"
    link rel: "stylesheet", href: "fonts.css"
    link rel: 'icon', type: 'image/x-icon', href: 'favicon.ico'
  end
  body do
    #img.justicar(src: '/justicar.png', alt: 'Justicar', height: '400px')
    #h1 { "Hello world from Justicar" }
    div do
      h1 { "Catgirls Rodeo" }
    end
    img(src: 'rodeo_by_urasato.png').rodeo
    div.window_handler do
      #25.times do
      #  div.guide(style: "flex-basis: #{(220..350).to_a.sample}px") { 'red' }
      #end
      #end
      keys = Justicar::PreProcessor.articles.keys.sort
      keys.reverse_each do |key|
      #25.times do
        div.window do
          div.draggable(class: 'title-bar') do
            div(class: 'title-bar-text') { 
              key.to_s
            }
            div(class: 'title-bar-controls') do
              #button("aria-label": "Minimize")
              button("aria-label": "Maximize").maximize
              button("aria-label": "Close").close
            end
          end
          div(class: "window-body", style: "width: #{(250..450).to_a.sample}px") { 
            Justicar::PreProcessor.articles[key]
          }
        end
      end
=begin
  h2.paggio do
    'Hello world from Paggi!'
  end
  p.paggio do
    "This part was generated by Paggio in HTML :)"
  end
=end
    end
  end
    script type: "text/javascript", src: "script.js"
end
