require 'opal'
require 'native'
require 'promise'
require 'browser/setup/full'

Position = Struct.new(:x, :y)
mouse = Struct.new(:x, :y, :drag).new(0, 0, false)
$maximized = Struct.new(:x, :y, :width, :height, :element).new(0, 0, 0, 0, false)


def maximize_window(element)
  if $maximized.element
    $maximized.element = false
    element.style.apply {
      top $maximized.y.px
      left $maximized.x.px
    }
    element.at_css('.window-body').style.apply {
      width $maximized.width.px
      height $maximized.height.px
    }
  else
    $maximized.element = element
    $maximized.x = element.position.x
    $maximized.y = element.position.y
    $maximized.width = element.at_css('.window-body').width
    $maximized.height = element.at_css('.window-body').height
    element.style.apply {
      top 0.px
      left 0.px
    }
    element.at_css('.window-body').style.apply {
      width ($document.window.size.inner_width - 16).px
      height ($document.window.size.inner_height - 44).px
    }
  end
end

$document.ready do
  draggable = $document.css('.draggable')
  windows = $document.css('.window')

  puts draggable.to_ary

  draggable_cached_position = []
  draggable.each do |element|
    draggable_cached_position.push Position.new(
      element.parent.position.x,
      element.parent.position.y,
    )
  end
  draggable.each_with_index do |element, index|
    element.parent.style.apply {
      top draggable_cached_position[index].y.px
      left draggable_cached_position[index].x.px
      position 'absolute'
      z index: draggable.length - index
    }
  end


  # maximizes windows
  windows.each do |element|
    element.on(:click, '.maximize') do |e|
      e.prevent
      maximize_window(element)
    end
    element.on(:dblclick, '.title-bar') do |e|
      maximize_window(element)
    end
  end

  # re-sort windows when one is clicked on
  windows.each do |element|
    element.on :mousedown do |e|
      draggable.unshift draggable.delete(element.at_css('.title-bar'))
      draggable.each_with_index do |elem, index|
        elem.parent.style.apply {
          z index: draggable.length - index
        }
      end
    end
  end

  # set window to "drag" mode when clicked on and reset when let go
  draggable.each do |element|
    element.on :mousedown do |e|
      next if $maximized.element
      mouse.drag = element
      mouse.x = e.page.x - element.parent.position.x
      mouse.y = e.page.y - element.parent.position.y
      element.parent.style.apply {
        top (e.page.y.px - mouse.y).px
        left (e.page.x.px - mouse.x).px
        position 'absolute'
      }
      $document.one :mouseup do |e|
        mouse.drag = false
      end
    end
  end

  # when a window is in "drag" mode, move window to mouse cursor
  $document.on :mousemove do |e|
    if mouse.drag
      mouse.drag.parent.style.apply {
        top (e.page.y.px - mouse.y).px
        left (e.page.x.px - mouse.x).px
      }
    end
  end
=begin
  DOM do
    h2.opal do
      "Hello World from Opal!"
    end
    p.opal {"This part was generated by Opal from Javascript (:"}
    h2.articles do
      "Here is some articles that were generated using the processing system:"
    end
    p.articles do 
      a(href: '/articles').articles { "Articles" }
    end
  end.append_to($document.body)
=end
end
